# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
   config.vm.synced_folder "html", "/var/www/html/"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3
    apt-get install -y pyton3-pip
    apt-get install -y neovim
    apt-get install -y apache2
    SHELL
end
